var words = [{'eng': ['abstain'], 'korMain': ['자제하다', '삼가다'], 'korAccept': [''], 'mean': 'to avoid doing something that may be enjoyable but also may not be healthy or safe'}, 
{'eng': ['controversial'], 'korMain': ['논란이 분분한', '논쟁적인'], 'korAccept': [''], 'mean': 'causing strong disagreement'}, 
{'eng': ['contradict'], 'korMain': ['반박하다', '모순되다'], 'korAccept': [''], 'mean': 'say the opposite of what someone has said is true'}, 
{'eng': ['flaw'], 'korMain': ['결함'], 'korAccept': [''], 'mean': 'a mistake or fault in something'}, 
{'eng': ['intake'], 'korMain': ['섭취량'], 'korAccept': [''], 'mean': 'the amount of something that you eat or drink'}, 
{'eng': ['tricky'], 'korMain': ['어려운', '다루기 힘든'], 'korAccept': [''], 'mean': 'difficult to do or deal with'}, 
{'eng': ['predisposed'], 'korMain': ['~하는 경향이 있는'], 'korAccept': [''], 'mean': 'likely to think, feel or behave in a particular way'}, 
{'eng': ['beneficial'], 'korMain': ['의로운', '긍정적인 영향을 미치는'], 'korAccept': [''], 'mean': 'having a good effect'}, 
{'eng': ['persist'], 'korMain': ['지속되다', '계속되다'], 'korAccept': [''], 'mean': 'to continue'}, 
{'eng': ['impact'], 'korMain': ['영향', '결과', '충격'], 'korAccept': [''], 'mean': 'the effect that something has'}, 
{'eng': ['cardiovascular disease'], 'korMain': ['심혈관질환'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['sophisticated'], 'korMain': ['정교한'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['coronary'], 'korMain': ['관상동맥의'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['mathodological'], 'korMain': ['방법론적인'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['inflated'], 'korMain': ['부풀린'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['sensible type'], 'korMain': ['현명한 사람'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['liable to'], 'korMain': ['~할 가능성이 있다'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['mortality'], 'korMain': ['사망률'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['stroke'], 'korMain': ['뇌졸증'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['intestinal'], 'korMain': ['장과 관련된', '장의'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['breast cancer'], 'korMain': ['유방암'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['in turning against'], 'korMain': ['(~에 반대하여) 등을 돌리다'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['conscience'], 'korMain': ['양심'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['hygiene'], 'korMain': ['위생'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['funded'], 'korMain': ['기금을 지원하다'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['promoted'], 'korMain': ['촉진하다'], 'korAccept': [''], 'mean': ''}, 
{'eng': ['link'], 'korMain': ['연관', '연결'], 'korAccept': [''], 'mean': ''}]

main(words);