var words = [
    {'eng': ['BCI'], 'korMain': ['뇌-컴퓨터 인터페이스'], 'korAccept': [], 'mean': 'Brain-Computer Interface'},
    {'eng': ['implant'], 'korMain': ['이식하다'], 'korAccept': [], 'mean': ''},
    {'eng': ['invasive'], 'korMain': ['침습적'], 'korAccept': [], 'mean': ''},
    {'eng': ['vet', 'veterinarian'], 'korMain': ['수의사'], 'korAccept': [], 'mean': ''},
    {'eng': ['debilitating'], 'korMain': ['쇠약하게 하는'], 'korAccept': [], 'mean': "making somebody's body or mind weaker"},
    {'eng': ['result in'], 'korMain': ['야기하다', '~를 낳다'], 'korAccept': [], 'mean': '원인 → 결과<br>The typhoon resulted in many thousands of deaths.'},
    {'eng': ['result from'], 'korMain': ['기인하다', '인하다'], 'korAccept': [], 'mean': '결과 → 원인'},
    {'eng': ['charge'], 'korMain': ['(앞으로) 돌진하다'], 'korAccept': ['돌진하다', '앞으로 돌진하다'], 'mean': ''},
    {'eng': ['sew'], 'korMain': ['꿰매다', '봉합하다'], 'korAccept': [], 'mean': '-sewn-sewn'},
    {'eng': ['symbiosis'], 'korMain': ['공생'], 'korAccept': [], 'mean': 'a mutually beneficial relationship'},
    {'eng': ['trigger'], 'korMain': ['촉발시키다'], 'korAccept': [], 'mean': '= cause, set off, excite '},
    {'eng': ['suppress'], 'korMain': ['억제하다'], 'korAccept': [], 'mean': ''},
    {'eng': ['refine'], 'korMain': ['정제하다', '개선하다'], 'korAccept': [], 'mean': 'improve by making small changes'},
    {'eng': ['paralysis'], 'korMain': ['마비'], 'korAccept': [], 'mean': ''},
    {'eng': ['paralyze'], 'korMain': ['마비시키다'], 'korAccept': [], 'mean': ''},
    {'eng': ['electric impulse'], 'korMain': ['전기 충격'], 'korAccept': [], 'mean': '= action potential, spike'},
    {'eng': ['propagation'], 'korMain': ['전도'], 'korAccept': [], 'mean': ''},
    {'eng': ['approval'], 'korMain': ['승인'], 'korAccept': [], 'mean': ''},
    {'eng': ['spike'], 'korMain': ['극파'], 'korAccept': [], 'mean': ''},
    {'eng': ['skeptical', 'sceptical'], 'korMain': ['회의적인'], 'korAccept': [], 'mean': ''},
    {'eng': ['boewl'], 'korMain': ['장'], 'korAccept': [], 'mean': ''},
    {'eng': ['vowel'], 'korMain': ['모음'], 'korAccept': [], 'mean': ''},
    {'eng': ['consonant'], 'korMain': ['자음'], 'korAccept': [], 'mean': ''},
    {'eng': ['bladder'], 'korMain': ['방광'], 'korAccept': [], 'mean': ''},
    {'eng': ['depression'], 'korMain': ['우울증'], 'korAccept': [], 'mean': ''},
    {'eng': ['dementia'], 'korMain': ['치매'], 'korAccept': [], 'mean': ''},
    {'eng': ['enormous'], 'korMain': ['(정상을 넘어설 정도로) 거대한', '엄청난'], 'korAccept': ['거대한', '엄청난'], 'mean': ''},
    {'eng': ['barrier'], 'korMain': ['장벽'], 'korAccept': [], 'mean': ''},
    {'eng': ['mainstream'], 'korMain': ['주류'], 'korAccept': [], 'mean': ''},
    {'eng': ['meticulous'], 'korMain': ['꼼꼼한', '세심한'], 'korAccept': [], 'mean': 'very vareful and precise '},
    {'eng': ['cutting-edge'], 'korMain': ['최첨단'], 'korAccept': [], 'mean': ''},
    {'eng': ['existential'], 'korMain': ['존재론적인'], 'korAccept': [], 'mean': ''}
]

main(words);