var words = [
    {'eng': ['inkblot'], 'korMain': ['잉크 반점'], 'korAccept': ['반점', '얼룩'], 'mean': ''},
    {'eng': ['Thematic Apperception Test'], 'korMain': ['주제통각검사'], 'korAccept': [], 'mean': ''},
    {'eng': ['make up'], 'korMain': ['화장하다', '구성하다', '화해하다', '꾸미다'], 'korAccept': ['조작하다'], 'mean': "He made up an excuse about his being.<br>Girls make up 30% of the students.<br>Why don't you two kiss and make up? "},
    {'eng': ['sore'], 'korMain': ['아픈', '화가 난'], 'korAccept': [], 'mean': '= annoyed, wound '},
    {'eng': ['grouch'], 'korMain': ['불평이 많은 사람'], 'korAccept': [], 'mean': ''},
    {'eng': ['pull'], 'korMain': ['저지르다', '수작을 부리다'], 'korAccept': [], 'mean': 'succeed in playing a trick on somebody '},
    {'eng': ['look up'], 'korMain': ['찾아보다'], 'korAccept': [], 'mean': 'look after, look at, look into, look up to, look down on '},
    {'eng': ['scale'], 'korMain': ['저울', '천칭'], 'korAccept': [], 'mean': ''},
    {'eng': ['mislead'], 'korMain': ['오도하다'], 'korAccept': [], 'mean': ''},
    {'eng': ['feeble'], 'korMain': ['유약한'], 'korAccept': ['연약한'], 'mean': ''},
    {'eng': ['get carried away'], 'korMain': ['~에 열중 하다', '흥분하다'], 'korAccept': [], 'mean': ''},
    {'eng': ['get used to'], 'korMain': ['~에 익숙해지다'], 'korAccept': [], 'mean': ''},
    {'eng': ['get along'], 'korMain': ['잘 지내다'], 'korAccept': [], 'mean': ''},
    {'eng': ['nothing but'], 'korMain': ['오직', '그저'], 'korAccept': [], 'mean': '= only '},
    {'eng': ['anything but'], 'korMain': ['~이 결코 아닌'], 'korAccept': [], 'mean': '= not<br>The luxurious hotel was anything but cheap '},
    {'eng': ['opportunist'], 'korMain': ['기회주의자'], 'korAccept': [], 'mean': ''},
    {'eng': ['big-shot'], 'korMain': ['거물'], 'korAccept': [], 'mean': ''},
    {'eng': ['soak'], 'korMain': ['흠씬 젖다'], 'korAccept': ['젖다'], 'mean': ''},
    {'eng': ['petition'], 'korMain': ['진정서'], 'korAccept': ['탄원서', '청원서'], 'mean': ''},
    {'eng': ['despise'], 'korMain': ['깔보다'], 'korAccept': [], 'mean': '= look down on '},
    {'eng': ['sensation'], 'korMain': ['감각', '사회적 파문'], 'korAccept': ['반향'], 'mean': ''},
    {'eng': ['tangible'], 'korMain': ['분명히 실재하는', '구체적인'], 'korAccept': ['구상적인'], 'mean': ''},
    {'eng': ['intangible'], 'korMain': ['무형의', '뭐라고 말할 수 없는'], 'korAccept': [], 'mean': ''},
    {'eng': ['inferiority complex'], 'korMain': ['열등 의식'], 'korAccept': [], 'mean': ''},
    {'eng': ['refute'], 'korMain': ['반박하다'], 'korAccept': ['논박하다'], 'mean': ''},
    {'eng': ['refutation'], 'korMain': ['반박'], 'korAccept': ['논박'], 'mean': 'The error is too obvious to require a particular refutation '},
    {'eng': ['ward off'], 'korMain': ['물리치다', '막다'], 'korAccept': [], 'mean': 'ward off danger/evil spirits '},
    {'eng': ['rowdy'], 'korMain': ['소란스러운', '난폭한'], 'korAccept': [], 'mean': ''},
    {'eng': ['at one’s expense'], 'korMain': ['~의 희생으로'], 'korAccept': [], 'mean': ''},
    {'eng': ['vacuous'], 'korMain': ['멍청한', '얼빠진', '텅 빈'], 'korAccept': [], 'mean': ''},
    {'eng': ['mentally retarded'], 'korMain': ['정신박약'], 'korAccept': ['정신지체'], 'mean': ''},
    {'eng': ['infuriate'], 'korMain': ['분노하게 만들다'], 'korAccept': [], 'mean': ''},
    {'eng': ['illiteracy'], 'korMain': ['문맹'], 'korAccept': [], 'mean': ''},
    {'eng': ['naïveté', 'naivete'], 'korMain': ['순진함', '소박함'], 'korAccept': [], 'mean': ''},
    {'eng': ['naïve', 'naive'], 'korMain': ['순진해 빠진', '순진한'], 'korAccept': [], 'mean': ''},
    {'eng': ['vicious'], 'korMain': ['잔인한', '악(의)'], 'korAccept': [], 'mean': 'the vicious circle of poverty '},
    {'eng': ['regression'], 'korMain': ['퇴행'], 'korAccept': [], 'mean': ''},
    {'eng': ['disprove'], 'korMain': ['반증하다', '틀렸음을 입증 하다'], 'korAccept': [], 'mean': ''},
    {'eng': ['obscure'], 'korMain': ['흐릿하게 만들다'], 'korAccept': ['모호하게 만들다'], 'mean': ''},
    {'eng': ['co-ordination'], 'korMain': ['협응'], 'korAccept': [], 'mean': ''},
    {'eng': ['amnesia'], 'korMain': ['기억상실증'], 'korAccept': [], 'mean': ''},
    {'eng': ['dementia'], 'korMain': ['치매'], 'korAccept': [], 'mean': ''},
    {'eng': ['deterioration'], 'korMain': ['하락', '퇴보', '악화'], 'korAccept': [], 'mean': ''},
    {'eng': ['intensification'], 'korMain': ['강화'], 'korAccept': [], 'mean': ''},
    {'eng': ['absent-minded'], 'korMain': ['건망증', '멍한'], 'korAccept': [], 'mean': ''},
    {'eng': ['dissection'], 'korMain': ['해부'], 'korAccept': [], 'mean': ''},
    {'eng': ['cerebral convolution'], 'korMain': ['대뇌주름'], 'korAccept': [], 'mean': ''},
    {'eng': ['fissure'], 'korMain': ['열구'], 'korAccept': [], 'mean': ''},
    {'eng': ['introspective'], 'korMain': ['자기성찰적인', '내성적인'], 'korAccept': ['성찰적인'], 'mean': ''},
    {'eng': ['fugue'], 'korMain': ['푸가'], 'korAccept': [], 'mean': 'a period during which a person suffers from loss of memory, often begins a new life, and, upon recovery, remembers nothing of the amnesic phase '},
    {'eng': ['senility'], 'korMain': ['노화', '노년'], 'korAccept': [], 'mean': ''},
    {'eng': ['guts'], 'korMain': ['배짱'], 'korAccept': [], 'mean': ''},
    {'eng': ['for good'], 'korMain': ['영원히'], 'korAccept': [], 'mean': '= forever'}
]

main(words);