var words = [
    {"korAccept": [], "eng": ["suddenly"], "korMain": ["갑자기", "불현듯"], "mean": ""}, 
    {"korAccept": [], "eng": ["immediately"], "korMain": ["즉시", "즉각"], "mean": ""}, 
    {"korAccept": [], "eng": ["probably"], "korMain": ["아마"], "mean": ""}, 
    {"korAccept": [], "eng": ["frequently"], "korMain": ["자주", "흔히"], "mean": ""}, 
    {"korAccept": [], "eng": ["closely"], "korMain": ["자세히"], "mean": ""}, 
    {"korAccept": [], "eng": ["eventually"], "korMain": ["결국"], "mean": ""}, 
    {"korAccept": [], "eng": ["worry"], "korMain": ["걱정하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["dazzle"], "korMain": ["눈이 부시게 하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["predict"], "korMain": ["예측하다"], "mean": ""}, 
    {"korAccept": ["~을 보다"], "eng": ["observe"], "korMain": ["관찰하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["rely"], "korMain": ["의지하다", "신뢰하다", "믿다"], "mean": ""}, 
    {"korAccept": [], "eng": ["accurate"], "korMain": ["정확한", "정밀한"], "mean": ""}, 
    {"korAccept": [], "eng": ["sensation"], "korMain": ["감각"], "mean": ""}, 
    {"korAccept": [], "eng": ["declarative memory"], "korMain": ["서술적 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["episodic memory"], "korMain": ["일화 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["autobigraphical memory"], "korMain": ["자서전적 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["semantic memory"], "korMain": ["의미 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["procedural memory"], "korMain": ["절차 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["explicit memory"], "korMain": ["명시적 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["implicit memory"], "korMain": ["묵시적 기억"], "mean": ""}, 
    {"korAccept": [], "eng": ["consolidation"], "korMain": ["고착화", "응고화"], "mean": "새로운 기억 정보가 해마의 영향력을 벗어나 해당 피질 등의 부위에 독립적으로 장기 기억화되는 현상"}, 
    {"korAccept": [], "eng": ["retention"], "korMain": ["파지"], "mean": "기억된 것을 보존하는 것"}, 
    {"korAccept": [], "eng": ["stimulus"], "korMain": ["자극"], "mean": ""}, 
    {"korAccept": ["놀라운"], "eng": ["astonishing"], "korMain": ["정말 놀라운", "믿기 힘든"], "mean": ""}, 
    {"korAccept": [], "eng": ["memory capacity"], "korMain": ["기억 용량"], "mean": ""}, 
    {"korAccept": [], "eng": ["incredible"], "korMain": ["믿을 수 없는", "믿기 힘든"], "mean": ""}, 
    {"korAccept": [], "eng": ["hyperthymesia"], "korMain": ["과잉기억증후군"], "mean": ""}, 
    {"korAccept": ["칭하다"], "eng": ["refer to A as B"], "korMain": ["A를 B라 칭하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["mnemonist"], "korMain": ["기억술사"], "mean": ""}, 
    {"korAccept": ["생산하다"], "eng": ["come up with"], "korMain": ["~을 생산하다"], "mean": "produce something"}, 
    {"korAccept": [], "eng": ["diagonal"], "korMain": ["사선의"], "mean": ""}, 
    {"korAccept": [], "eng": ["recall"], "korMain": ["회상하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["sloppy"], "korMain": ["엉성한", "헐렁한"], "mean": "careless and loose"}, 
    {"korAccept": [], "eng": ["syn(a)esthesia"], "korMain": ["공감각"], "mean": ""}, 
    {"korAccept": [], "eng": ["evoke"], "korMain": ["불러일으키다"], "mean": ""}, 
    {"korAccept": [], "eng": ["multimodal"], "korMain": ["복합양태성"], "mean": "다양한 (감각) 모드를 활용하는"}, 
    {"korAccept": [], "eng": ["stump"], "korMain": ["난감하게 만들다"], "mean": ""}, 
    {"korAccept": [], "eng": ["complement"], "korMain": ["보완하다", "보충하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["imaginary"], "korMain": ["상상의"], "mean": ""}, 
    {"korAccept": [], "eng": ["association"], "korMain": ["연상", "연합"], "mean": ""}, 
    {"korAccept": ["이로운"], "eng": ["to one's advantage"], "korMain": ["~에게 이로운"], "mean": ""}, 
    {"korAccept": [], "eng": ["interfere with"], "korMain": ["방해하다", "저해하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["integrate"], "korMain": ["통합하다"], "mean": ""}, 
    {"korAccept": [], "eng": ["bewildering"], "korMain": ["당혹스러운"], "mean": ""}, 
    {"korAccept": ["폭격을 하듯 쏟아붓다", "쏟아붓다"], "eng": ["bombard"], "korMain": ["(폭격을 하듯) 쏟아붓다"], "mean": ""}, 
    {"korAccept": [], "eng": ["segregation"], "korMain": ["분리", "구별"], "mean": ""}, 
    {"korAccept": [], "eng": ["malleable"], "korMain": ["가소적인", "말랑말랑한"], "mean": ""}
    ];

main(words);