var words = [{'eng': ['manipulate'], 'korMain': ['조작하다'], 'korAccept': [], 'mean': ''},
{'eng': ['crucial'], 'korMain': ['중요한', '중대한', '결정적인'], 'korAccept': [], 'mean': ''},
{'eng': ['revolutionize'], 'korMain': ['(급격한) 변화를 가져오다'], 'korAccept': ['변화를 가져오다', '급격한 변화를 가져오다'], 'mean': ''},
{'eng': ['sophisticated'], 'korMain': ['정교한'], 'korAccept': [], 'mean': ''},
{'eng': ['algorithms'], 'korMain': ['알고리즘'], 'korAccept': [], 'mean': ''},
{'eng': ['LiDAR'], 'korMain': ['빛 탐지 거리 및 측정'], 'korAccept': [], 'mean': 'LIght Detection And Ranging'},
{'eng': ['stereo'], 'korMain': ['입체 음향 (시스템)'], 'korAccept': ['입체 음향', '입체 음향 시스템'], 'mean': ''},
{'eng': ['replicas'], 'korMain': ['복제본'], 'korAccept': [], 'mean': ''},
{'eng': ['twins'], 'korMain': ['쌍둥이'], 'korAccept': [], 'mean': ''},
{'eng': ['sustainable'], 'korMain': ['지속 가능한'], 'korAccept': [], 'mean': ''},
{'eng': ['consumption'], 'korMain': ['소비'], 'korAccept': [], 'mean': ''},
{'eng': ['patterns'], 'korMain': ['패턴', '양식'], 'korAccept': [], 'mean': ''},
{'eng': ['transition'], 'korMain': ['전환'], 'korAccept': [], 'mean': ''},
{'eng': ['establish'], 'korMain': ['설립하다', '수립하다'], 'korAccept': [], 'mean': ''},
{'eng': ['linear'], 'korMain': ['선형적인'], 'korAccept': [], 'mean': ''},
{'eng': ['finite'], 'korMain': ['유한한'], 'korAccept': [], 'mean': ''},
{'eng': ['staggering'], 'korMain': ['엄청난'], 'korAccept': [], 'mean': ''},
{'eng': ['inclusive'], 'korMain': ['포괄적인'], 'korAccept': [], 'mean': ''},
{'eng': ['equitable'], 'korMain': ['공평한'], 'korAccept': [], 'mean': ''},
{'eng': ['literacy'], 'korMain': ['문해력'], 'korAccept': [], 'mean': ''},
{'eng': ['numeracy'], 'korMain': ['산술 능력', '수리 감각'], 'korAccept': [], 'mean': ''},
{'eng': ['marginalized'], 'korMain': ['(사회적으로) 소외된', '무시된'], 'korAccept': ['소외된', '무시된', '사회적으로 소외된', '사회적으로 무시된'], 'mean': ''},
{'eng': ['targets'], 'korMain': ['목표', '대상'], 'korAccept': [], 'mean': ''},
{'eng': ['persistent'], 'korMain': ['지속적인'], 'korAccept': [], 'mean': ''},
{'eng': ['accessible'], 'korMain': ['접근 가능한'], 'korAccept': [], 'mean': ''},
{'eng': ['projected'], 'korMain': ['예상된'], 'korAccept': [], 'mean': ''},
{'eng': ['devastating'], 'korMain': ['(대단히) 파괴적인'], 'korAccept': ['대단히 파괴적인', '파괴적인'], 'mean': ''}]

main(words);